(() => {
  "use strict";
  const q = (selector) => document.querySelector(selector);
  const ui = { login:q("#loginView"),dashboard:q("#dashboard"),loginForm:q("#loginForm"),password:q("#password"),loginError:q("#loginError"),logout:q("#logoutButton"),refresh:q("#refreshButton"),body:q("#applicationsBody"),empty:q("#emptyState"),updated:q("#lastUpdated"),search:q("#searchInput"),filters:q("#filters"),total:q("#totalCount"),submitted:q("#submittedCount"),drafts:q("#draftCount"),owners:q("#ownerCount"),offerForm:q("#offerForm"),quoteSelect:q("#quoteSelect"),driverSelect:q("#driverSelect"),offerRate:q("#offerRate"),offerNotes:q("#offerNotes"),offerError:q("#offerError"),quoteList:q("#quoteList"),offerList:q("#offerList") };
  let applications=[],quotes=[],drivers=[],offers=[],activeFilter="all",refreshTimer;
  const experience={under_1:"Less than 1 year","1_plus":"1+ year","2_plus":"2+ years","3_plus":"3+ years","4_plus":"4+ years"},availability={tomorrow:"Tomorrow",this_week:"This week",more_than_week:"More than a week"};
  function showLogin(){ui.login.hidden=false;ui.dashboard.hidden=true;ui.logout.hidden=true;clearInterval(refreshTimer)}
  function showDashboard(){ui.login.hidden=true;ui.dashboard.hidden=false;ui.logout.hidden=false;refreshAll();clearInterval(refreshTimer);refreshTimer=setInterval(refreshAll,5000)}
  function textCell(value,className){const cell=document.createElement("td");if(className)cell.className=className;cell.textContent=value||"—";return cell}
  function applicantCell(app){const cell=document.createElement("td");cell.className="applicant";const name=document.createElement("strong");name.textContent=app.full_name||"Name not entered";cell.append(name);if(app.email){const email=document.createElement("a");email.href=`mailto:${app.email}`;email.textContent=app.email;cell.append(email)}if(app.phone){const phone=document.createElement("a");phone.href=`tel:${app.phone}`;phone.textContent=app.phone;cell.append(phone)}if(app.cdl_document_uploaded_at){const cdl=document.createElement("a");cdl.href=`https://worldwide-cargo-express.edgeformmedia.workers.dev/api/admin/applications/${app.id}/documents/cdl`;cdl.target="_blank";cdl.rel="noopener";cdl.textContent="Download CDL";cell.append(cdl)}return cell}
  function statusCell(app){const cell=document.createElement("td"),badge=document.createElement("span");badge.className=`badge ${app.status}`;badge.textContent=app.status==="submitted"?"Submitted":"In progress";cell.append(badge);return cell}
  function detailsCell(app){const cell=document.createElement("td");cell.className="details";const strong=document.createElement("strong"),detail=document.createElement("span");detail.className="muted";if(app.driver_type==="owner_operator"){strong.textContent=app.truck_year?`${app.truck_year} truck`:"Truck not entered";detail.textContent=`${app.truck_mileage?`${Number(app.truck_mileage).toLocaleString()} mi`:"mileage pending"} · Plate: ${app.has_plate||"pending"}`}else{strong.textContent=`Amazon Relay: ${app.amazon_relay_experience||"pending"}`;detail.textContent=`Start: ${availability[app.start_availability]||"pending"}`}cell.append(strong,detail);return cell}
  function dateCell(app){const cell=document.createElement("td"),date=new Date(`${app.updated_at}${app.updated_at.endsWith("Z")?"":"Z"}`),strong=document.createElement("strong"),time=document.createElement("div");strong.textContent=date.toLocaleDateString([],{month:"short",day:"numeric",year:"numeric"});time.className="muted";time.textContent=date.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"});cell.append(strong,time);return cell}
  function renderApplications(){const query=ui.search.value.trim().toLowerCase(),visible=applications.filter((app)=>(activeFilter==="all"||app.status===activeFilter)&&(!query||[app.full_name,app.email,app.phone].some((value)=>String(value||"").toLowerCase().includes(query))));ui.body.replaceChildren();for(const app of visible){const row=document.createElement("tr");row.append(statusCell(app),applicantCell(app),textCell(app.driver_type==="owner_operator"?"Owner-operator":"Company driver"),textCell(experience[app.experience]||"—"),detailsCell(app),dateCell(app));ui.body.append(row)}ui.empty.hidden=visible.length!==0;ui.total.textContent=applications.length;ui.submitted.textContent=applications.filter((app)=>app.status==="submitted").length;ui.drafts.textContent=applications.filter((app)=>app.status==="draft").length;ui.owners.textContent=applications.filter((app)=>app.driver_type==="owner_operator").length}
  function option(value,label){const item=document.createElement("option");item.value=value;item.textContent=label;return item}
  function matchEmpty(container,text){const item=document.createElement("div");item.className="match-empty";item.textContent=text;container.replaceChildren(item)}
  function renderMatching(){const chosenQuote=ui.quoteSelect.value,chosenDriver=ui.driverSelect.value;ui.quoteSelect.replaceChildren(option("","Choose a quote"),...quotes.filter((quote)=>!["booked","declined"].includes(quote.status)).map((quote)=>option(quote.id,`${quote.pickup_city}, ${quote.pickup_state} → ${quote.delivery_city}, ${quote.delivery_state} · ${quote.company_name}`)));ui.driverSelect.replaceChildren(option("","Choose a driver"),...drivers.map((driver)=>option(driver.id,`${driver.full_name} · ${driver.driver_type==="owner_operator"?"Owner-operator":"Company driver"}`)));ui.quoteSelect.value=chosenQuote;ui.driverSelect.value=chosenDriver;
    if(!quotes.length)matchEmpty(ui.quoteList,"No submitted quotes yet.");else ui.quoteList.replaceChildren(...quotes.map((quote)=>{const item=document.createElement("article"),title=document.createElement("strong"),detail=document.createElement("p"),select=document.createElement("select");item.className="match-item";title.textContent=`${quote.pickup_city}, ${quote.pickup_state} → ${quote.delivery_city}, ${quote.delivery_state}`;detail.textContent=`${quote.company_name} · ${quote.equipment} · ${Number(quote.total_weight||0).toLocaleString()} lb`;select.dataset.quote=quote.id;["new","reviewing","quoted","booked","declined"].forEach((value)=>select.append(option(value,value[0].toUpperCase()+value.slice(1))));select.value=quote.status;item.append(title,detail,select);return item}));
    if(!offers.length)matchEmpty(ui.offerList,"No driver offers sent yet.");else ui.offerList.replaceChildren(...offers.map((offer)=>{const quote=quotes.find((item)=>item.id===offer.quote_id),item=document.createElement("article"),title=document.createElement("strong"),detail=document.createElement("p");item.className="match-item";title.textContent=offer.driver_name;const amount=offer.offered_rate_cents==null?"Rate open":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(offer.offered_rate_cents/100);detail.textContent=`${quote?`${quote.pickup_city}, ${quote.pickup_state} → ${quote.delivery_city}, ${quote.delivery_state}`:"Quote"} · ${amount} · ${offer.status}`;item.append(title,detail);return item}))}
  async function refreshAll(){try{const [appsResponse,quotesResponse]=await Promise.all([fetch("/api/admin/applications",{cache:"no-store"}),fetch("/api/admin/quotes",{cache:"no-store"})]);if(appsResponse.status===401||quotesResponse.status===401){showLogin();return}if(!appsResponse.ok||!quotesResponse.ok)throw new Error();const appData=await appsResponse.json(),quoteData=await quotesResponse.json();applications=appData.applications;quotes=quoteData.quotes;drivers=quoteData.drivers;offers=quoteData.offers;renderApplications();renderMatching();ui.updated.textContent=`Live view · updated ${new Date().toLocaleTimeString([],{hour:"numeric",minute:"2-digit",second:"2-digit"})}`}catch{ui.updated.textContent="Unable to refresh. Trying again shortly."}}
  ui.loginForm.addEventListener("submit",async(event)=>{event.preventDefault();ui.loginError.textContent="";const button=ui.loginForm.querySelector("button");button.disabled=true;try{const response=await fetch("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password:ui.password.value})});if(!response.ok)throw new Error("Incorrect password.");ui.password.value="";showDashboard()}catch(error){ui.loginError.textContent=error.message}finally{button.disabled=false}});
  ui.logout.addEventListener("click",async()=>{await fetch("/api/admin/logout",{method:"POST"});showLogin()});ui.refresh.addEventListener("click",refreshAll);ui.search.addEventListener("input",renderApplications);ui.filters.addEventListener("click",(event)=>{const button=event.target.closest("button[data-filter]");if(!button)return;activeFilter=button.dataset.filter;ui.filters.querySelectorAll("button").forEach((item)=>item.classList.toggle("active",item===button));renderApplications()});
  ui.offerForm.addEventListener("submit",async(event)=>{event.preventDefault();ui.offerError.textContent="";const button=ui.offerForm.querySelector("button");button.disabled=true;try{const response=await fetch("/api/admin/offers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({quoteId:ui.quoteSelect.value,driverAccountId:ui.driverSelect.value,offeredRate:ui.offerRate.value.replaceAll(",",""),notes:ui.offerNotes.value})}),data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to send offer.");ui.offerRate.value="";ui.offerNotes.value="";await refreshAll()}catch(error){ui.offerError.textContent=error.message}finally{button.disabled=false}});
  ui.quoteList.addEventListener("change",async(event)=>{const select=event.target.closest("select[data-quote]");if(!select)return;select.disabled=true;const response=await fetch(`/api/admin/quotes/${select.dataset.quote}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status:select.value})});if(response.ok)await refreshAll();else select.disabled=false});
  fetch("/api/admin/session",{cache:"no-store"}).then((response)=>response.ok?showDashboard():showLogin()).catch(showLogin);
})();
